# Generated by Django 5.0.4 on 2024-04-03 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outfits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothes_type', models.CharField(max_length=900)),
                ('clothes_image', models.CharField(max_length=900)),
                ('clothes_price', models.IntegerField()),
            ],
        ),
    ]
